apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deploy-1
  template:
    metadata:
      labels:
        app: deploy-1
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sleep","3600"]          