apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy01
  template:
    metadata:
      labels:
        app: deploy01
    spec:
      containers:
      - name: nginx-container
        image:  nginx
        ports:
        - containerPort: 80        