apiVersion: v1
kind: Pod
metadata:
  name: secret-pod-volume
spec:
  containers:
    - name: my-container
      image: nginx
      volumeMounts:
        - name: secret-volume
          mountPath: "/secrets"
  volumes:
    - name: secret-volume
      secret:
        secretName: my-secret
  restartPolicy: Never
